USE panaderia;
DELIMITER //
CREATE FUNCTION FN_NOMBRECLIENTE(P_ID INT)
RETURNS VARCHAR(50)
DETERMINISTIC
BEGIN
DECLARE NOMBRE VARCHAR(50);
	SELECT NOMBRECLIENTE INTO NOMBRE FROM CLIENTES WHERE ID_CLIENTES=P_ID;
RETURN NOMBRE;
END //
DELIMITER ; 
SELECT FN_NOMBRECLIENTE(1);

DELIMITER //
CREATE FUNCTION FN_DATOSCLIENTES(P_ID INT)
RETURNS VARCHAR(50)
DETERMINISTIC
BEGIN
DECLARE NOMBRE VARCHAR(50);
	SELECT concat(NOMBRECLIENTE
					
                    ,' '
                    , TELEFONO
                    ,' '
                    ,CALLE
                    ,' '
                    ,NRO
                    ,' '
                    ,CP) INTO NOMBRE FROM CLIENTES WHERE ID_CLIENTES=P_ID;
RETURN NOMBRE;
END //
DELIMITER ; 
SELECT FN_DATOSCLIENTES(1);