CREATE TABLE LOG_CAMBIOS (
    ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
    TABLA_AFECTADA VARCHAR(50),
    OPERACION_REALIZADA VARCHAR(50),
    FECHA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER Trigger_Agregar_Pedido
AFTER INSERT ON PEDIDOS
FOR EACH ROW

    INSERT INTO LOG_CAMBIOS (TABLA_AFECTADA, OPERACION_REALIZADA)
    VALUES ('PEDIDOS', 'Inserción de nuevo pedido');
    
CREATE TRIGGER Trigger_Agregar_Telefono
AFTER UPDATE ON CLIENTES
FOR EACH ROW

    INSERT INTO LOG_CAMBIOS (TABLA_AFECTADA, OPERACION_REALIZADA)
    VALUES ('CLIENTES', 'Actualización de teléfono de cliente');

CREATE TRIGGER Trigger_Eliminar_Pedido
AFTER DELETE ON PEDIDOS
FOR EACH ROW

    INSERT INTO LOG_CAMBIOS (TABLA_AFECTADA, OPERACION_REALIZADA)
    VALUES ('PEDIDOS', 'Eliminación de pedido');


CREATE TRIGGER Trigger_Actualizar_Pedido
AFTER INSERT ON PEDIDOS
FOR EACH ROW

    UPDATE DETALLEPEDIDOS
    SET TOTAL = CalcularTotalPedido(NEW.ID_PEDIDO)
    WHERE ID_PEDIDO = NEW.ID_PEDIDO;

CREATE TRIGGER Trigger_Actualizar_Telefono
AFTER UPDATE ON CLIENTES
FOR EACH ROW

    INSERT INTO LOG_CAMBIOS (TABLA_AFECTADA, OPERACION_REALIZADA)
    VALUES ('CLIENTES', 'Actualización de teléfono de cliente');

CREATE TRIGGER Trigger_Suprimir_Pedido
AFTER DELETE ON PEDIDOS
FOR EACH ROW

    INSERT INTO LOG_CAMBIOS (TABLA_AFECTADA, OPERACION_REALIZADA)
    VALUES ('PEDIDOS', 'Suprimir pedido');
