USE panaderia;
CREATE OR REPLACE VIEW VW_NOMBRE_MAYUSCULA AS 
SELECT ucase(nombrecliente) FROM clientes;

SELECT * FROM VW_NOMBRE_MAYUSCULA;

CREATE OR REPLACE VIEW VW_NOMBRE_NEGRITA AS 
SELECT ucase(nombreproducto) FROM productos;

CREATE OR REPLACE VIEW VW_VENTAS_REALIZADAS AS 
SELECT SUM(cantidadpedida) FROM pedidos WHERE fecha_hora LIKE'2024-04-26%';

SELECT * FROM VW_VENTAS_REALIZADAS;

CREATE OR REPLACE VIEW VW_RAZON_SOCIAL_LL AS
SELECT ucase(razon_social) FROM la_linda;

SELECT*FROM VW_RAZON_SOCIAL_LL;

CREATE OR REPLACE VIEW VW_NOMBREVENDEDOR_MINUSCULA AS
SELECT ucase(nombrevendedor) FROM vendedores;

SELECT*FROM VW_NOMBREVENDEDOR_MINUSCULA;