CREATE OR REPLACE VIEW VW_NOMBRE_MAYUSCULA AS 
SELECT ucase(NOMBRECLIENTE) FROM CLIENTES;

SELECT *FROM VW_NOMBRE_MAYUSCULA;

CREATE OR REPLACE VIEW VW_NOMBRE_NEGRITA AS 
SELECT ucase(NOMBREPROODUCTO) FROM PRODUCTOS;

CREATE OR REPLACE VIEW VW_VENTAS_REALIZADAS AS 
SELECT SUM(CANTIDADPEDIDA) FROM PEDIDOS WHERE FECHA_HORA LIKE'2024-04-26%';

SELECT*FROM VW_VENTAS_REALIZADAS;

CREATE OR REPLACE VIEW VW_RAZON_SOCIAL_LL AS
SELECT ucase(RAZON_SOCIAL) FROM LA_LINDA;

SELECT*FROM VW_RAZON_SOCIAL_LL;

CREATE OR REPLACE VIEW VW_NOMBREVENDEDOR_MINUSCULA AS
SELECT ucase(NOMBREVENDEDOR) FROM VENDEDORES;

SELECT*FROM VW_NOMBREVENDEDOR_MINUSCULA;