
DROP DATABASE PANADERIA;
-- DROP DATABASE PANADERIA;
CREATE DATABASE PANADERIA;
USE PANADERIA;
-- drop schema if exists Panaderia;
CREATE TABLE LA_LINDA(
ID_LL INT PRIMARY KEY,
RAZON_SOCIAL VARCHAR(20),
CUIT VARCHAR(20),
TEL VARCHAR(30)
);
CREATE TABLE PEDIDOS(
ID_PEDIDO INT PRIMARY KEY NOT NULL AUTO_INCREMENT
, ID_CLIENTE INT
, ID_VENDEDOR INT
, ID_PRODUCTO INT
, CANTIDADPEDIDA INT 
, FECHA_HORA DATETIME NOT NULL
);



CREATE TABLE CLIENTES (
ID_CLIENTES INT PRIMARY KEY NOT NULL AUTO_INCREMENT
, ID_LL INT 
, NOMBRECLIENTE VARCHAR(100) DEFAULT 'NOEXISTE'
, TELEFONO VARCHAR(20) NOT NULL
, CALLE VARCHAR(20) NOT NULL
, NRO VARCHAR(10) NOT NULL
, CP VARCHAR(10)
);
CREATE TABLE DETALLEPEDIDOS(
ID_DETALLEPEDIDO INT PRIMARY KEY NOT NULL AUTO_INCREMENT
, ID_PEDIDO INT
, TOTAL FLOAT
);
CREATE TABLE VENDEDORES(
ID_VENDEDORES INT PRIMARY KEY NOT NULL AUTO_INCREMENT
, NOMBREVENDEDOR VARCHAR(20) NOT NULL
);
CREATE TABLE PRODUCTOS(
ID_PRODUCTOS INT PRIMARY KEY NOT NULL AUTO_INCREMENT
, ID_LL INT
, NOMBREPROODUCTO VARCHAR(20)
, PRECIO INT
);

-- ALTER TABLE NOMBRE TABLA
-- ADD CONSTRAINT NOMBRE DE LA CONSTRAINT DE LA FK
-- FOREIGN KEY(NOMBRE DE LA COLUMNA EN LA TABLA ELEGIDA) REFERENCES TABLA PADRE(PK DE LA TABLA PADRE)

ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_PEDIDOS_CLIENTES 
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTES);

ALTER TABLE PEDIDOS 
ADD CONSTRAINT FK_PEDIDOS_VENDEDORES
FOREIGN KEY(ID_VENDEDOR) REFERENCES VENDEDORES(ID_VENDEDORES);

ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_PEDIDOS_PRODUCTOS
FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTOS);

ALTER TABLE DETALLEPEDIDOS
ADD CONSTRAINT FK_DETALLEPEDIDOS_PEDIDOS
FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO);

ALTER TABLE PRODUCTOS
ADD CONSTRAINT FK_PRODUCTOS_LL
FOREIGN KEY(ID_LL) REFERENCES LA_LINDA(ID_LL);

ALTER TABLE CLIENTES
ADD CONSTRAINT FK_CLIENTES_LL
FOREIGN KEY(ID_LL) REFERENCES LA_LINDA(ID_LL);









